//
// Floppy layout generated by FloppyBuilder 1.3
//

#ifdef ASSEMBLER
//
// Information for the Assembler
//
#ifdef LOADER
FileStartSector .byt 135,133,136,137,12
FileStartTrack .byt 0,3,3,3,3
FileSizeLow .byt <38085,<760,<1120,<1024,<1536
FileSizeHigh .byt >38085,>760,>1120,>1024,>1536
#undef LOADER
#endif // LOADER
#undef ASSEMBLER
#else
//
// Information for the Compiler
//
#endif

//
// Summary for this floppy building session:
//
#define FLOPPY_SIDE_NUMBER 2    // Number of sides
#define FLOPPY_TRACK_NUMBER 42    // Number of tracks
#define FLOPPY_SECTOR_PER_TRACK 17   // Number of sectors per track

#define FLOPPY_LOADER_TRACK 0   // Track where the loader is stored
#define FLOPPY_LOADER_SECTOR 4   // Sector where the loader is stored
#define FLOPPY_LOADER_ADDRESS 64768   // Address where the loader is loaded on boot ($fd00)

//
// List of files written to the floppy
//
// Entry #0 '..\build\files\RomlessGame.o'
// - Starts on  track 0 sector 7 and is 49 sectors long (12461 compressed bytes: 32% of 38085 bytes).
// Entry #1 '..\build\files\Font6x8.hir'
// - Starts on  track 3 sector 5 and is 3 sectors long (556 compressed bytes: 73% of 760 bytes).
// Entry #2 '..\data\screen.bin'
// - Starts on  track 3 sector 8 and is 1 sectors long (209 compressed bytes: 18% of 1120 bytes).
// Entry #3 '..\data\stdchar.bin'
// - Starts on  track 3 sector 9 and is 3 sectors long (591 compressed bytes: 57% of 1024 bytes).
// Entry #4 'Reserved sectors'
// - Starts on  track 3 sector 12 and is 6 sectors long (1536 bytes).
//
// 68 sectors used, out of 1428. (4% of the total disk size used)
//
#define LOADER_SECTOR_BUFFER $200
#define LOADER_BASE_ZERO_PAGE $F2
#define LOADER_GAME_PROGRAM 0
#define LOADER_GAME_PROGRAM_ADDRESS $400
#define LOADER_GAME_PROGRAM_TRACK 0
#define LOADER_GAME_PROGRAM_SECTOR 135
#define LOADER_GAME_PROGRAM_SIZE 38085
#define LOADER_GAME_PROGRAM_SIZE_COMPRESSED 12461
#define LOADER_FONT_6x8 1
#define BASIC_SCREEN 2
#define LOADER_CHARSET_STANDARD 3

//
// Metadata
//
#ifdef METADATA_STORAGE

#endif // METADATA_STORAGE

